CREATE TABLE `cps530`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `productId` INT NULL,
  `Qty` INT NULL,
  `orderTimestamp` DATETIME NULL,
  `credit_card_number` NVARCHAR(20) NULL,
  `credit_card_holder` VARCHAR(255) NULL,
  `expiry_month` VARCHAR(10) NULL,
  `expiry_year` VARCHAR(10) NULL,
  `credit_card_first_name` VARCHAR(100) NULL,
  `credit_card_last_name` VARCHAR(100) NULL,
  `credit_card_address_line_1` NVARCHAR(255) NULL,
  `credit_card_address_line_2` NVARCHAR(255) NULL,
  `country` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  PRIMARY KEY (`orderId`));
